default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    database: terminal_control_api_development
  queue:
    <<: *primary_development
    database: terminal_control_api_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: terminal_control_api_development_cable
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: terminal_control_api_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  queue:
    <<: *primary_production
    database: terminal_control_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: terminal_control_api_production_cable
    migrations_paths: db/cable_migrate
  cache:
    <<: *primary_production
    database: terminal_control_api_production_cache
