default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: terminal_control_api_development

test:
  <<: *default
  database: terminal_control_api_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

