default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= Rails.application.credentials.dig(:db, :host) %>
  port: 6543
  username: <%= Rails.application.credentials.dig(:db, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= Rails.application.credentials.dig(:db, :name) %>

test:
  <<: *default
  database: <%= Rails.application.credentials.dig(:db, :name) %>

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:db, :name) %>
