development:
  block_unpaid_taxpayer_terminals:
    class: BlockTaxpayerTerminalsJob
    queue: terminal_blocking
    schedule: "every 10 minutes"

  subscription_expiry_check:
    class: SubscriptionExpiryJob
    queue: subscription_reminders
    schedule: "every 10 minutes"

production:
  block_unpaid_taxpayer_terminals:
    class: BlockTaxpayerTerminalsJob
    queue: terminal_blocking
    schedule: "every 10 minutes"

  subscription_expiry_check:
    class: SubscriptionExpiryJob
    queue: subscription_reminders
    schedule: "every 10 minutes"

