development:
  block_unpaid_taxpayer_terminals:
    class: BlockTaxpayerTerminalsJob
    queue: terminal_blocking
    schedule: "every day at 3:00am"

  subscription_expiry_check:
    class: SubscriptionExpiryJob
    queue: subscription_reminders
    schedule: "every day at 3:00am"

production:
  block_unpaid_taxpayer_terminals:
    class: BlockTaxpayerTerminalsJob
    queue: terminal_blocking
    schedule: "every day at 3:00am"

  subscription_expiry_check:
    class: SubscriptionExpiryJob
    queue: subscription_reminders
    schedule: "every day at 3:00am"


