name: Keep Render API Awake

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping API Endpoint to Trigger Job
        run: curl -s ${{ secrets.RENDER_API_URL }}/internal/ping_dashboard > /dev/null
